spring:
  profiles: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 8080